# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-18 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_url', models.CharField(max_length=255)),
                ('local_path', models.CharField(max_length=255)),
                ('file_name', models.CharField(max_length=255)),
            ],
        ),
    ]
