# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-19 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20171018_0928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='web_url',
            new_name='web_url_full',
        ),
        migrations.AddField(
            model_name='images',
            name='web_url_raw',
            field=models.CharField(default='none', max_length=255),
            preserve_default=False,
        ),
    ]
