# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-19 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("data", "0003_auto_20171019_0915")]

    operations = [
        migrations.AlterField(
            model_name="images",
            name="file_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="images",
            name="local_path",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
