# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-19 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("data", "0004_auto_20171019_0924")]

    operations = [
        migrations.AddField(
            model_name="images",
            name="is_saved",
            field=models.BooleanField(default=False),
        )
    ]
